// <auto-generated />
using System;
using Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(HshopContext))]
    [Migration("20241022150609_SeedDataCategories")]
    partial class SeedDataCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82c66893-29a5-441d-9949-8b4a560714e4"),
                            Description = "Aliquid totam tempore ab quibusdam.",
                            Name = "Outdoors",
                            PictureUrl = "https://picsum.photos/640/480/?image=757",
                            Slug = "outdoors"
                        },
                        new
                        {
                            Id = new Guid("0f18c462-a8db-4866-8afe-f5e7ec234449"),
                            Description = "A voluptatibus deserunt recusandae ut.",
                            Name = "Toys",
                            PictureUrl = "https://picsum.photos/640/480/?image=600",
                            Slug = "toys"
                        },
                        new
                        {
                            Id = new Guid("ea735b72-db54-4355-bd29-33c11a1fc398"),
                            Description = "Maiores quo veritatis ut error.",
                            Name = "Garden",
                            PictureUrl = "https://picsum.photos/640/480/?image=517",
                            Slug = "garden"
                        },
                        new
                        {
                            Id = new Guid("fc614e1b-772c-4054-ba87-230f6c4eb5c4"),
                            Description = "Sit aut labore qui error.",
                            Name = "Sports",
                            PictureUrl = "https://picsum.photos/640/480/?image=523",
                            Slug = "sports"
                        },
                        new
                        {
                            Id = new Guid("5b4991fe-fb40-4977-8a14-845e5462d0cc"),
                            Description = "Veritatis sint earum nihil ea.",
                            Name = "Books",
                            PictureUrl = "https://picsum.photos/640/480/?image=472",
                            Slug = "books"
                        },
                        new
                        {
                            Id = new Guid("6e734e3f-7038-4d0e-aaf0-cb807d92ba3f"),
                            Description = "Quis eveniet eum velit numquam.",
                            Name = "Tools",
                            PictureUrl = "https://picsum.photos/640/480/?image=726",
                            Slug = "tools"
                        },
                        new
                        {
                            Id = new Guid("c3234771-e8fb-4ae9-ac85-1e46cdb0c837"),
                            Description = "Laboriosam reprehenderit quaerat et nihil.",
                            Name = "Books",
                            PictureUrl = "https://picsum.photos/640/480/?image=731",
                            Slug = "books"
                        },
                        new
                        {
                            Id = new Guid("2edbd264-d3ad-4d20-aa46-d59028a59197"),
                            Description = "Ex accusantium voluptas et occaecati.",
                            Name = "Toys",
                            PictureUrl = "https://picsum.photos/640/480/?image=173",
                            Slug = "toys"
                        },
                        new
                        {
                            Id = new Guid("e86830b1-f6cb-4242-9fdf-98481345c303"),
                            Description = "Est laborum delectus magnam velit.",
                            Name = "Clothing",
                            PictureUrl = "https://picsum.photos/640/480/?image=298",
                            Slug = "clothing"
                        },
                        new
                        {
                            Id = new Guid("279322c6-eb4b-46e8-b2e6-0396d29ee384"),
                            Description = "Iste aut illo a quae.",
                            Name = "Tools",
                            PictureUrl = "https://picsum.photos/640/480/?image=491",
                            Slug = "tools"
                        },
                        new
                        {
                            Id = new Guid("7d841ef7-6c21-490f-996d-44eac28866ff"),
                            Description = "In consequatur modi tenetur consequatur.",
                            Name = "Books",
                            PictureUrl = "https://picsum.photos/640/480/?image=256",
                            Slug = "books"
                        },
                        new
                        {
                            Id = new Guid("2b6bea56-381f-40b5-9741-664a80448fd5"),
                            Description = "Magnam voluptatem dolore veritatis officia.",
                            Name = "Sports",
                            PictureUrl = "https://picsum.photos/640/480/?image=734",
                            Slug = "sports"
                        },
                        new
                        {
                            Id = new Guid("b149843d-acd7-49e3-ad2f-dcf737854528"),
                            Description = "Nihil molestias nesciunt quasi quo.",
                            Name = "Electronics",
                            PictureUrl = "https://picsum.photos/640/480/?image=349",
                            Slug = "electronics"
                        },
                        new
                        {
                            Id = new Guid("d920a123-7f23-454b-8628-c0b871f4a049"),
                            Description = "Et ipsam eaque cumque veritatis.",
                            Name = "Tools",
                            PictureUrl = "https://picsum.photos/640/480/?image=814",
                            Slug = "tools"
                        },
                        new
                        {
                            Id = new Guid("d5fdbaf6-43d5-43b3-9766-2ad9d07a5c64"),
                            Description = "Et rem facere eligendi voluptatem.",
                            Name = "Beauty",
                            PictureUrl = "https://picsum.photos/640/480/?image=390",
                            Slug = "beauty"
                        },
                        new
                        {
                            Id = new Guid("22b8cd1c-2116-48d1-86ad-946a979a74be"),
                            Description = "Quia impedit facere ea qui.",
                            Name = "Toys",
                            PictureUrl = "https://picsum.photos/640/480/?image=240",
                            Slug = "toys"
                        },
                        new
                        {
                            Id = new Guid("24d003bd-535a-418f-a975-5ca9ef353cfb"),
                            Description = "Maiores necessitatibus minus culpa ex.",
                            Name = "Books",
                            PictureUrl = "https://picsum.photos/640/480/?image=506",
                            Slug = "books"
                        },
                        new
                        {
                            Id = new Guid("7a04bb47-1b3d-4519-982d-b14d0d351750"),
                            Description = "Laborum ad accusantium dolorum minus.",
                            Name = "Sports",
                            PictureUrl = "https://picsum.photos/640/480/?image=612",
                            Slug = "sports"
                        },
                        new
                        {
                            Id = new Guid("1c763a10-49ac-4aea-b880-9c1120c31a08"),
                            Description = "Quisquam aut laboriosam culpa blanditiis.",
                            Name = "Clothing",
                            PictureUrl = "https://picsum.photos/640/480/?image=398",
                            Slug = "clothing"
                        },
                        new
                        {
                            Id = new Guid("5b327f92-32ad-4241-994a-383c82536d4d"),
                            Description = "Consequatur ut dolore qui illum.",
                            Name = "Clothing",
                            PictureUrl = "https://picsum.photos/640/480/?image=572",
                            Slug = "clothing"
                        },
                        new
                        {
                            Id = new Guid("a6ff0571-0c12-4cf9-a821-14b4f0a75ff3"),
                            Description = "Voluptatibus aut voluptate non repudiandae.",
                            Name = "Tools",
                            PictureUrl = "https://picsum.photos/640/480/?image=715",
                            Slug = "tools"
                        },
                        new
                        {
                            Id = new Guid("4334652b-ec62-4364-b686-f0edd48d7cc9"),
                            Description = "Qui maxime quia dolor dolorem.",
                            Name = "Jewelery",
                            PictureUrl = "https://picsum.photos/640/480/?image=1010",
                            Slug = "jewelery"
                        },
                        new
                        {
                            Id = new Guid("cccd69ba-5eb2-47a8-b99b-92cf6c4e2494"),
                            Description = "Accusamus vero dolore quisquam est.",
                            Name = "Games",
                            PictureUrl = "https://picsum.photos/640/480/?image=553",
                            Slug = "games"
                        },
                        new
                        {
                            Id = new Guid("092b2f04-c372-4486-800b-ed25387f74fd"),
                            Description = "Tempore id provident sit placeat.",
                            Name = "Clothing",
                            PictureUrl = "https://picsum.photos/640/480/?image=438",
                            Slug = "clothing"
                        },
                        new
                        {
                            Id = new Guid("32bc8b83-d905-41a3-8ab0-1961e41c345b"),
                            Description = "Sit optio doloribus consequatur distinctio.",
                            Name = "Games",
                            PictureUrl = "https://picsum.photos/640/480/?image=685",
                            Slug = "games"
                        },
                        new
                        {
                            Id = new Guid("7b755e97-d232-4798-95c0-f1816b50f1da"),
                            Description = "Aliquid qui quia harum iure.",
                            Name = "Clothing",
                            PictureUrl = "https://picsum.photos/640/480/?image=370",
                            Slug = "clothing"
                        },
                        new
                        {
                            Id = new Guid("494858bb-9a95-4096-a1a8-6c5ba67d8fa7"),
                            Description = "Sed odio nobis minima aut.",
                            Name = "Games",
                            PictureUrl = "https://picsum.photos/640/480/?image=911",
                            Slug = "games"
                        },
                        new
                        {
                            Id = new Guid("7cae1b06-f23a-4310-97e5-0c3fe8876464"),
                            Description = "Blanditiis aspernatur odio rem deserunt.",
                            Name = "Grocery",
                            PictureUrl = "https://picsum.photos/640/480/?image=87",
                            Slug = "grocery"
                        },
                        new
                        {
                            Id = new Guid("c51026f9-eaaf-40b9-a7a3-104b9e8bf9cd"),
                            Description = "Minima delectus ut voluptatum amet.",
                            Name = "Tools",
                            PictureUrl = "https://picsum.photos/640/480/?image=131",
                            Slug = "tools"
                        },
                        new
                        {
                            Id = new Guid("85c8a889-f731-4387-b1db-12fedd7ad980"),
                            Description = "Recusandae laboriosam quas amet fuga.",
                            Name = "Industrial",
                            PictureUrl = "https://picsum.photos/640/480/?image=200",
                            Slug = "industrial"
                        },
                        new
                        {
                            Id = new Guid("d509922f-f4f0-4cf4-863b-103341b4ac03"),
                            Description = "Odio rerum eius quo facilis.",
                            Name = "Outdoors",
                            PictureUrl = "https://picsum.photos/640/480/?image=730",
                            Slug = "outdoors"
                        },
                        new
                        {
                            Id = new Guid("2ad99874-95b1-444d-b600-b095e824420d"),
                            Description = "Nam tempora ducimus sed rem.",
                            Name = "Toys",
                            PictureUrl = "https://picsum.photos/640/480/?image=266",
                            Slug = "toys"
                        },
                        new
                        {
                            Id = new Guid("b23cf752-591a-4bd7-90b2-eb9e420ea5c5"),
                            Description = "Natus earum occaecati ducimus fugiat.",
                            Name = "Jewelery",
                            PictureUrl = "https://picsum.photos/640/480/?image=483",
                            Slug = "jewelery"
                        },
                        new
                        {
                            Id = new Guid("94c3acee-3ce0-4814-afe6-3c0dac3d62e1"),
                            Description = "Consequatur beatae quidem fugit labore.",
                            Name = "Garden",
                            PictureUrl = "https://picsum.photos/640/480/?image=823",
                            Slug = "garden"
                        },
                        new
                        {
                            Id = new Guid("4d0f1bbe-e130-4081-a555-d53b2380c530"),
                            Description = "Et illum necessitatibus eius alias.",
                            Name = "Games",
                            PictureUrl = "https://picsum.photos/640/480/?image=1023",
                            Slug = "games"
                        },
                        new
                        {
                            Id = new Guid("c818c5e8-f953-4c37-876e-11c72d744776"),
                            Description = "Consequatur voluptatem sit sint autem.",
                            Name = "Clothing",
                            PictureUrl = "https://picsum.photos/640/480/?image=921",
                            Slug = "clothing"
                        },
                        new
                        {
                            Id = new Guid("52c0fd41-9633-4190-b7fd-0a170f81c77f"),
                            Description = "Quo necessitatibus rerum rerum ullam.",
                            Name = "Sports",
                            PictureUrl = "https://picsum.photos/640/480/?image=810",
                            Slug = "sports"
                        },
                        new
                        {
                            Id = new Guid("be0573a5-7862-4a7d-9d23-5a58378edca6"),
                            Description = "Nemo dolorum ullam distinctio omnis.",
                            Name = "Toys",
                            PictureUrl = "https://picsum.photos/640/480/?image=357",
                            Slug = "toys"
                        },
                        new
                        {
                            Id = new Guid("ef55fb05-f737-4594-a814-c73b9ea59e19"),
                            Description = "Ipsam quis corporis culpa est.",
                            Name = "Home",
                            PictureUrl = "https://picsum.photos/640/480/?image=824",
                            Slug = "home"
                        },
                        new
                        {
                            Id = new Guid("e22049e0-d2bb-481d-ab5f-9ffec6b25b09"),
                            Description = "Incidunt minima provident iure qui.",
                            Name = "Grocery",
                            PictureUrl = "https://picsum.photos/640/480/?image=372",
                            Slug = "grocery"
                        },
                        new
                        {
                            Id = new Guid("d375d349-7e19-45e8-acb2-97ab292485cb"),
                            Description = "Odit accusantium non autem nostrum.",
                            Name = "Automotive",
                            PictureUrl = "https://picsum.photos/640/480/?image=242",
                            Slug = "automotive"
                        },
                        new
                        {
                            Id = new Guid("8c2b742c-1230-4fab-a1e6-a2048118cca9"),
                            Description = "Suscipit rerum ab nisi molestias.",
                            Name = "Jewelery",
                            PictureUrl = "https://picsum.photos/640/480/?image=823",
                            Slug = "jewelery"
                        },
                        new
                        {
                            Id = new Guid("45070b03-f23c-4c6b-9be4-db8805ef8e45"),
                            Description = "Distinctio laborum facilis velit nihil.",
                            Name = "Jewelery",
                            PictureUrl = "https://picsum.photos/640/480/?image=880",
                            Slug = "jewelery"
                        },
                        new
                        {
                            Id = new Guid("d321eb70-ade3-43bb-b22e-0745381cd8ad"),
                            Description = "Natus cumque tempore perferendis quos.",
                            Name = "Baby",
                            PictureUrl = "https://picsum.photos/640/480/?image=403",
                            Slug = "baby"
                        },
                        new
                        {
                            Id = new Guid("bcaf1b09-508f-41bd-a25f-4b868bd1d1a5"),
                            Description = "Et beatae autem quod enim.",
                            Name = "Movies",
                            PictureUrl = "https://picsum.photos/640/480/?image=1028",
                            Slug = "movies"
                        },
                        new
                        {
                            Id = new Guid("d6334dae-1066-4739-84fa-47430f74a7e2"),
                            Description = "Recusandae amet qui sunt tempora.",
                            Name = "Health",
                            PictureUrl = "https://picsum.photos/640/480/?image=4",
                            Slug = "health"
                        },
                        new
                        {
                            Id = new Guid("760972f9-fde3-495b-b757-cd87a0047d47"),
                            Description = "Error nihil quod quasi architecto.",
                            Name = "Automotive",
                            PictureUrl = "https://picsum.photos/640/480/?image=526",
                            Slug = "automotive"
                        },
                        new
                        {
                            Id = new Guid("4a4ebc57-0151-484b-be70-1e5dc3f68806"),
                            Description = "Vero porro animi est minus.",
                            Name = "Computers",
                            PictureUrl = "https://picsum.photos/640/480/?image=836",
                            Slug = "computers"
                        },
                        new
                        {
                            Id = new Guid("1b0f7bdb-06b2-4bd4-84f8-c3dc9f07830f"),
                            Description = "Consequatur quo deserunt quia ut.",
                            Name = "Beauty",
                            PictureUrl = "https://picsum.photos/640/480/?image=779",
                            Slug = "beauty"
                        },
                        new
                        {
                            Id = new Guid("101d0b00-7a81-429c-a123-9b4bfcfaf77d"),
                            Description = "Earum consequatur porro sunt similique.",
                            Name = "Computers",
                            PictureUrl = "https://picsum.photos/640/480/?image=327",
                            Slug = "computers"
                        });
                });

            modelBuilder.Entity("Core.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Core.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("192cc891-7804-4471-ad70-e73739f62256"),
                            Address = "74047 Howe Flats, South Randimouth, Tanzania",
                            Description = "Excepturi esse eaque ab debitis et distinctio perferendis possimus repellendus.",
                            Email = "Vivienne38@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=935",
                            Name = "Mraz - Crooks",
                            PhoneNumber = "0999515393"
                        },
                        new
                        {
                            Id = new Guid("b6a2a793-d515-4186-86ad-576812c29f96"),
                            Address = "4333 Wilderman Harbors, New Trey, Belarus",
                            Description = "Delectus nam et repellat nisi aut ea deserunt sequi fugit.",
                            Email = "Maeve91@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=1083",
                            Name = "Lehner Group",
                            PhoneNumber = "0979655368"
                        },
                        new
                        {
                            Id = new Guid("581c3271-c341-4900-b794-a3c1986b342a"),
                            Address = "8024 Mayer Brook, South Tyresetown, Cambodia",
                            Description = "Expedita quo reiciendis ut veniam ut non laudantium dolorum sunt.",
                            Email = "Thea44@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=58",
                            Name = "Willms LLC",
                            PhoneNumber = "0937277577"
                        },
                        new
                        {
                            Id = new Guid("26ae25a2-4fbd-41cc-95aa-d173fa5f0b11"),
                            Address = "4270 Cornell Lodge, North Kaci, Svalbard & Jan Mayen Islands",
                            Description = "Ducimus sed et in doloribus a ut est pariatur vero.",
                            Email = "Skye.Koss38@gmail.com",
                            Logo = "https://picsum.photos/640/480/?image=179",
                            Name = "O'Hara - Gaylord",
                            PhoneNumber = "0959457061"
                        },
                        new
                        {
                            Id = new Guid("c89cdfd5-b8e9-44bc-91b0-796518f85715"),
                            Address = "653 Nasir Falls, South Jaydechester, Brazil",
                            Description = "Facilis sunt libero reiciendis unde perferendis autem perferendis autem autem.",
                            Email = "Markus_Ledner@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=160",
                            Name = "Beer Group",
                            PhoneNumber = "0947275534"
                        },
                        new
                        {
                            Id = new Guid("43a237ae-2dd6-4e38-93a1-6106b9a834cc"),
                            Address = "5834 Ida Branch, Corwinburgh, Vanuatu",
                            Description = "Sequi nemo quia nostrum enim quis quia et natus vel.",
                            Email = "Jayde27@yahoo.com",
                            Logo = "https://picsum.photos/640/480/?image=715",
                            Name = "Bogan - Kihn",
                            PhoneNumber = "0983072538"
                        },
                        new
                        {
                            Id = new Guid("634972ed-cd93-4e41-883b-f3a5aba33015"),
                            Address = "539 Hessel Roads, Lake Neha, Belgium",
                            Description = "Velit et adipisci fuga odio quos magnam nesciunt omnis at.",
                            Email = "Marlene34@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=176",
                            Name = "Barrows, Crist and Crist",
                            PhoneNumber = "0965323186"
                        },
                        new
                        {
                            Id = new Guid("8d7b0e8f-91d1-42e9-997d-4ac849c2f5f8"),
                            Address = "836 Weimann Mills, South Daniela, Sierra Leone",
                            Description = "In dolores omnis et placeat ipsum et enim eos doloribus.",
                            Email = "Jared.Ferry35@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=803",
                            Name = "White - Hilll",
                            PhoneNumber = "0978197890"
                        },
                        new
                        {
                            Id = new Guid("61a39879-0740-4218-8753-51909d2acdf6"),
                            Address = "0546 Angelica Corners, Melynahaven, France",
                            Description = "Nihil facilis accusamus in rem id eos quo et similique.",
                            Email = "Laila.Dickens@yahoo.com",
                            Logo = "https://picsum.photos/640/480/?image=292",
                            Name = "Flatley - Pfannerstill",
                            PhoneNumber = "0948697815"
                        },
                        new
                        {
                            Id = new Guid("6874dfb0-6362-45c4-b319-1542c5b7d7c3"),
                            Address = "81589 Hilpert Knolls, Welchfurt, Syrian Arab Republic",
                            Description = "Odio ad odit voluptatibus ab velit reprehenderit distinctio non quis.",
                            Email = "Noemie.Ferry40@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=1066",
                            Name = "Sauer, Kub and Mills",
                            PhoneNumber = "0973046843"
                        },
                        new
                        {
                            Id = new Guid("1fb8b9a9-e08a-4014-96c4-df86bab7ae91"),
                            Address = "121 Anahi Cove, North Reese, Democratic People's Republic of Korea",
                            Description = "Eius qui reprehenderit sunt vitae quasi labore accusamus vitae ipsum.",
                            Email = "Bernard.Ledner86@gmail.com",
                            Logo = "https://picsum.photos/640/480/?image=877",
                            Name = "Frami, Waelchi and Brekke",
                            PhoneNumber = "0979993802"
                        },
                        new
                        {
                            Id = new Guid("4359fcaf-17aa-4d85-a441-5c5f031dd87e"),
                            Address = "7377 Blick Crossroad, Faheystad, Solomon Islands",
                            Description = "Ipsam doloribus velit voluptatem est et nemo exercitationem molestiae sed.",
                            Email = "Mckayla_Graham18@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=488",
                            Name = "Runolfsdottir LLC",
                            PhoneNumber = "0953959300"
                        },
                        new
                        {
                            Id = new Guid("34563da3-1b83-49e7-8ab8-81bd61b797dc"),
                            Address = "53869 Hickle Stravenue, Reubenview, Saint Pierre and Miquelon",
                            Description = "Perferendis tempora ut amet ut aliquid consequuntur aperiam atque at.",
                            Email = "Lexus63@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=585",
                            Name = "Ryan Group",
                            PhoneNumber = "0957321869"
                        },
                        new
                        {
                            Id = new Guid("84788cb3-117a-4033-82e4-634af22688af"),
                            Address = "339 Hand Mountain, Port Jamey, Cameroon",
                            Description = "Ad quo distinctio eveniet dolores repudiandae voluptatem qui nulla voluptatem.",
                            Email = "Edythe_Koepp72@gmail.com",
                            Logo = "https://picsum.photos/640/480/?image=14",
                            Name = "Nader, Medhurst and Feest",
                            PhoneNumber = "0943594555"
                        },
                        new
                        {
                            Id = new Guid("16df4e1e-e65f-47da-b532-1a6c942582e1"),
                            Address = "501 Crist Divide, Port Yolanda, Saint Martin",
                            Description = "At tempore quas occaecati quaerat nesciunt ad quidem laudantium natus.",
                            Email = "Deborah.Gorczany6@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=584",
                            Name = "Kassulke, Veum and Christiansen",
                            PhoneNumber = "0916157366"
                        },
                        new
                        {
                            Id = new Guid("4f670930-8c87-468d-b2f6-69ca297c3347"),
                            Address = "7957 Daugherty Turnpike, Port Isom, Venezuela",
                            Description = "Voluptas recusandae facere itaque nobis possimus inventore rem consectetur natus.",
                            Email = "Destinee83@yahoo.com",
                            Logo = "https://picsum.photos/640/480/?image=183",
                            Name = "Klocko Group",
                            PhoneNumber = "0959340665"
                        },
                        new
                        {
                            Id = new Guid("d4b72356-1e5e-4f8e-91f6-8ca9c0bdb938"),
                            Address = "387 Torp Spurs, Hicklehaven, Tokelau",
                            Description = "Voluptates neque quo aut voluptas quas corrupti rerum consequatur consequatur.",
                            Email = "Luisa_Ondricka@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=554",
                            Name = "Fadel - Franecki",
                            PhoneNumber = "0915989149"
                        },
                        new
                        {
                            Id = new Guid("ded93312-ff02-4edb-82e9-b5ae9d8a0890"),
                            Address = "84130 Altenwerth Pass, East Travonburgh, Barbados",
                            Description = "Officiis quia praesentium sit earum nobis aut quis voluptatum rem.",
                            Email = "River.Grady@yahoo.com",
                            Logo = "https://picsum.photos/640/480/?image=142",
                            Name = "Quigley - Frami",
                            PhoneNumber = "0923346349"
                        },
                        new
                        {
                            Id = new Guid("eb9e31ca-e0a5-45a5-8aa4-96703064d33c"),
                            Address = "082 Sipes Squares, Kyleeborough, Belgium",
                            Description = "Maiores laboriosam aut quia eveniet iste repellat saepe eligendi reiciendis.",
                            Email = "Kaleigh.Altenwerth66@yahoo.com",
                            Logo = "https://picsum.photos/640/480/?image=593",
                            Name = "Hessel - O'Reilly",
                            PhoneNumber = "0982651411"
                        },
                        new
                        {
                            Id = new Guid("769a9e05-bd38-4569-a490-e7325cdb7ab7"),
                            Address = "193 Kuphal Greens, Lempishire, Samoa",
                            Description = "Velit aut aut sapiente quo architecto eum nesciunt debitis laudantium.",
                            Email = "Dario25@gmail.com",
                            Logo = "https://picsum.photos/640/480/?image=445",
                            Name = "Reynolds and Sons",
                            PhoneNumber = "0911104184"
                        },
                        new
                        {
                            Id = new Guid("365c5c5e-fb71-4379-bf05-060212ef21f4"),
                            Address = "99787 Quitzon Shore, New Mackenzie, Bouvet Island (Bouvetoya)",
                            Description = "Tenetur vel autem laudantium minus perspiciatis et fugit tempore ea.",
                            Email = "Kristy.Bosco79@gmail.com",
                            Logo = "https://picsum.photos/640/480/?image=662",
                            Name = "Cremin - Kutch",
                            PhoneNumber = "0974633345"
                        },
                        new
                        {
                            Id = new Guid("deb423e7-5a4f-4e18-aaf6-71eb63eda0b9"),
                            Address = "893 Bashirian Spring, South Alexieshire, Saint Pierre and Miquelon",
                            Description = "In deserunt rerum sit odit optio tenetur beatae accusamus architecto.",
                            Email = "Talon80@gmail.com",
                            Logo = "https://picsum.photos/640/480/?image=566",
                            Name = "O'Conner, Rutherford and Berge",
                            PhoneNumber = "0965570583"
                        },
                        new
                        {
                            Id = new Guid("c42efccd-e884-4fbc-924d-ee6e450bec0d"),
                            Address = "01423 Vandervort Mills, New Gildaland, Hungary",
                            Description = "A asperiores magni minus et nobis sed minima non qui.",
                            Email = "Melisa_Leuschke41@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=772",
                            Name = "Wyman LLC",
                            PhoneNumber = "0959926054"
                        },
                        new
                        {
                            Id = new Guid("31b17e45-8641-41d6-a59b-d2f67c965ec3"),
                            Address = "0553 Kshlerin Ridges, Shirleyview, Virgin Islands, U.S.",
                            Description = "Et inventore in aut quae voluptatem et omnis voluptas voluptate.",
                            Email = "Destiny.Ward47@gmail.com",
                            Logo = "https://picsum.photos/640/480/?image=715",
                            Name = "Renner LLC",
                            PhoneNumber = "0934487230"
                        },
                        new
                        {
                            Id = new Guid("3217f699-6d8e-47d3-ad67-82fd0de12309"),
                            Address = "7287 Corwin Walk, Reingerchester, Azerbaijan",
                            Description = "Nam et pariatur dignissimos nulla et laudantium et excepturi sequi.",
                            Email = "Eva49@yahoo.com",
                            Logo = "https://picsum.photos/640/480/?image=1051",
                            Name = "Gibson Group",
                            PhoneNumber = "0924474230"
                        },
                        new
                        {
                            Id = new Guid("e9e08747-9496-42d9-8ed5-b821cdc7621b"),
                            Address = "98281 Cyrus Mountain, East Ryan, Anguilla",
                            Description = "Id voluptate et tempore repellat natus corporis qui et voluptatum.",
                            Email = "Eugenia.Green72@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=897",
                            Name = "Considine Inc",
                            PhoneNumber = "0999309321"
                        },
                        new
                        {
                            Id = new Guid("63ab1917-26f2-4568-ada3-0af2d42d112d"),
                            Address = "1717 Frieda Crescent, Bernierstad, Colombia",
                            Description = "Tenetur nostrum voluptates qui debitis laborum cupiditate nulla repudiandae itaque.",
                            Email = "Wendell_Sporer89@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=244",
                            Name = "Bechtelar and Sons",
                            PhoneNumber = "0985298339"
                        },
                        new
                        {
                            Id = new Guid("8d34aa57-adbf-4baf-86e7-c22783d16039"),
                            Address = "29274 Aryanna Freeway, Jaydenland, Antigua and Barbuda",
                            Description = "Hic facere qui quis dicta tempora et vitae sequi qui.",
                            Email = "Carissa53@yahoo.com",
                            Logo = "https://picsum.photos/640/480/?image=560",
                            Name = "Maggio, Schiller and Conroy",
                            PhoneNumber = "0945754671"
                        },
                        new
                        {
                            Id = new Guid("d8e99e92-4889-48d8-b077-c9a35a067f0e"),
                            Address = "7669 Skiles Crossing, Pourosbury, Lithuania",
                            Description = "Exercitationem dicta fugit deleniti quasi totam omnis asperiores iusto quaerat.",
                            Email = "Thomas.Hammes79@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=926",
                            Name = "Shanahan Group",
                            PhoneNumber = "0978229441"
                        },
                        new
                        {
                            Id = new Guid("760e1acc-5532-47eb-b13c-0532c25ea486"),
                            Address = "08387 Spinka Square, New Aimeeshire, Malta",
                            Description = "Enim sed aut eligendi voluptatem sapiente quis rem dolorem molestiae.",
                            Email = "Polly22@yahoo.com",
                            Logo = "https://picsum.photos/640/480/?image=996",
                            Name = "Ferry - Bergstrom",
                            PhoneNumber = "0931387089"
                        },
                        new
                        {
                            Id = new Guid("95994515-f2d3-45a1-a069-9ef2d7284f10"),
                            Address = "947 Schroeder Mount, South Elysechester, Morocco",
                            Description = "Neque qui et doloremque aut quo porro repellendus ducimus pariatur.",
                            Email = "Kaylin87@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=332",
                            Name = "Mayert, Schumm and Dickens",
                            PhoneNumber = "0957456940"
                        },
                        new
                        {
                            Id = new Guid("a570ede0-d788-490c-b09d-d6e53de533ad"),
                            Address = "60894 Goldner Forest, South Rogelio, Cuba",
                            Description = "Praesentium quae dicta ullam exercitationem facilis a consectetur et et.",
                            Email = "Torey.Bayer40@yahoo.com",
                            Logo = "https://picsum.photos/640/480/?image=1066",
                            Name = "Steuber, Cartwright and Runte",
                            PhoneNumber = "0939359217"
                        },
                        new
                        {
                            Id = new Guid("1aab69ec-f826-4715-95e8-28e53a062304"),
                            Address = "70762 Harrison Estate, Micaelachester, Ireland",
                            Description = "Ab ea assumenda ut quos est aspernatur et deleniti fugiat.",
                            Email = "Daphne_Gleason@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=82",
                            Name = "Fisher - Heathcote",
                            PhoneNumber = "0966915262"
                        },
                        new
                        {
                            Id = new Guid("cd92c3c2-9106-417c-a0df-8df25d43f631"),
                            Address = "272 Rebecca Brooks, Hellerchester, Kazakhstan",
                            Description = "Voluptatem sapiente expedita ab et voluptates corrupti ad sed ut.",
                            Email = "Stanley_Stehr79@gmail.com",
                            Logo = "https://picsum.photos/640/480/?image=1009",
                            Name = "Cartwright and Sons",
                            PhoneNumber = "0955853699"
                        },
                        new
                        {
                            Id = new Guid("cedbc090-8e01-4ada-9448-8da5ba648f02"),
                            Address = "55242 Wilderman Drive, South Anamouth, Montenegro",
                            Description = "Quisquam quia voluptatem voluptatum ipsa dolor voluptatum consequatur animi ea.",
                            Email = "Arianna_Kilback80@gmail.com",
                            Logo = "https://picsum.photos/640/480/?image=1007",
                            Name = "Langosh, McLaughlin and Olson",
                            PhoneNumber = "0928057128"
                        },
                        new
                        {
                            Id = new Guid("f68f524a-6426-417d-803c-bf73f6df7fa4"),
                            Address = "7095 Reece Gardens, South Avis, Finland",
                            Description = "Non et cupiditate velit velit architecto laborum quis et et.",
                            Email = "Glenna.OConner@yahoo.com",
                            Logo = "https://picsum.photos/640/480/?image=997",
                            Name = "Ortiz and Sons",
                            PhoneNumber = "0917937716"
                        },
                        new
                        {
                            Id = new Guid("551cdd5a-dbba-4de6-a7f8-4d53e57e893b"),
                            Address = "322 Fanny Branch, West Julianville, Lesotho",
                            Description = "Ducimus suscipit voluptatum blanditiis consequuntur dolores dicta qui perferendis culpa.",
                            Email = "Marquis16@gmail.com",
                            Logo = "https://picsum.photos/640/480/?image=430",
                            Name = "Larson - Beer",
                            PhoneNumber = "0983910411"
                        },
                        new
                        {
                            Id = new Guid("8c8ef6ac-d24b-413a-b340-8306f31251b5"),
                            Address = "773 Florian Pike, East Camyllestad, Botswana",
                            Description = "Omnis eveniet voluptates animi et harum atque laudantium vitae magni.",
                            Email = "Ardith37@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=1050",
                            Name = "Bernier Inc",
                            PhoneNumber = "0981483378"
                        },
                        new
                        {
                            Id = new Guid("54e8a3be-0627-4d51-a656-267a6e7e0ea9"),
                            Address = "1747 Mann Turnpike, Lake Colin, Gibraltar",
                            Description = "Officia fugiat id dolor adipisci aut quas cumque totam nihil.",
                            Email = "Felipa83@yahoo.com",
                            Logo = "https://picsum.photos/640/480/?image=18",
                            Name = "Stamm LLC",
                            PhoneNumber = "0991730852"
                        },
                        new
                        {
                            Id = new Guid("811de89b-81d0-47ee-8e0a-011ba65d2406"),
                            Address = "711 Wunsch Road, Lednermouth, France",
                            Description = "Velit maxime quibusdam dolores est ullam placeat eum nemo qui.",
                            Email = "Casandra.Schultz48@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=664",
                            Name = "Glover - Labadie",
                            PhoneNumber = "0999599257"
                        },
                        new
                        {
                            Id = new Guid("7046a16c-8b84-4763-8886-03394853fd78"),
                            Address = "750 Zulauf Throughway, Lake Brennanstad, Andorra",
                            Description = "Et magni quia hic omnis eveniet placeat repellendus quaerat eveniet.",
                            Email = "Garth80@gmail.com",
                            Logo = "https://picsum.photos/640/480/?image=18",
                            Name = "Hamill - Ankunding",
                            PhoneNumber = "0991587763"
                        },
                        new
                        {
                            Id = new Guid("632f239c-b3e2-4b9b-92e7-fec25794a865"),
                            Address = "66106 Farrell Summit, North Orvalport, Kiribati",
                            Description = "Praesentium enim enim quas et aut adipisci voluptatem qui ipsum.",
                            Email = "Dariana.Stanton79@yahoo.com",
                            Logo = "https://picsum.photos/640/480/?image=78",
                            Name = "Conn, Mills and Parker",
                            PhoneNumber = "0986901943"
                        },
                        new
                        {
                            Id = new Guid("2a4ac1bc-dac3-4c76-8f51-818e933e0fb4"),
                            Address = "7199 Boehm Ways, Wehnerhaven, Guernsey",
                            Description = "Earum sit facere rerum ut laborum eos in perspiciatis ullam.",
                            Email = "Lloyd.Miller@yahoo.com",
                            Logo = "https://picsum.photos/640/480/?image=943",
                            Name = "Schmidt - Koepp",
                            PhoneNumber = "0945698899"
                        },
                        new
                        {
                            Id = new Guid("9c2e53f0-492d-43a9-9a83-55ce151e6d1a"),
                            Address = "715 Elmira Summit, Leliaside, French Southern Territories",
                            Description = "Temporibus temporibus ratione ex est dolor nesciunt perspiciatis aut modi.",
                            Email = "Lauretta68@gmail.com",
                            Logo = "https://picsum.photos/640/480/?image=397",
                            Name = "D'Amore, Rath and Legros",
                            PhoneNumber = "0964841451"
                        },
                        new
                        {
                            Id = new Guid("23787776-63df-43e1-9a55-456312daf4fe"),
                            Address = "5123 Lucie Rest, Betsyborough, Jordan",
                            Description = "Officia repellendus commodi excepturi harum ipsa modi sit mollitia quidem.",
                            Email = "Anthony75@hotmail.com",
                            Logo = "https://picsum.photos/640/480/?image=1058",
                            Name = "Morissette and Sons",
                            PhoneNumber = "0925158796"
                        },
                        new
                        {
                            Id = new Guid("5b389060-58b5-4be6-bdd8-0894a6a099fa"),
                            Address = "1794 Cordell Streets, Sawaynville, Ethiopia",
                            Description = "Dolores totam ex sit quod vero distinctio et ut ipsum.",
                            Email = "Reymundo.Kub30@yahoo.com",
                            Logo = "https://picsum.photos/640/480/?image=626",
                            Name = "Jenkins, Crooks and Harvey",
                            PhoneNumber = "0974574998"
                        },
                        new
                        {
                            Id = new Guid("0f10c22a-6e09-46f4-8f86-d5b493b1a017"),
                            Address = "65604 Electa Harbor, Kuhictown, Romania",
                            Description = "Consequatur rem aut deleniti sit beatae doloribus minus velit nobis.",
                            Email = "Cody_Weimann69@yahoo.com",
                            Logo = "https://picsum.photos/640/480/?image=440",
                            Name = "Keeling LLC",
                            PhoneNumber = "0936810970"
                        },
                        new
                        {
                            Id = new Guid("a0bb5ac8-e0af-48a5-ae7b-06d59dd743b8"),
                            Address = "255 Nienow Bridge, West Price, Latvia",
                            Description = "Consequatur cumque voluptas dolor esse ut porro sit laboriosam deserunt.",
                            Email = "Jeramy.Gleichner@yahoo.com",
                            Logo = "https://picsum.photos/640/480/?image=771",
                            Name = "Reilly - Crona",
                            PhoneNumber = "0982790128"
                        },
                        new
                        {
                            Id = new Guid("01ab6e36-ab3c-4dea-a0ce-23545264aca6"),
                            Address = "101 Herzog Meadow, Pearlinetown, Qatar",
                            Description = "Quis aut illum vitae similique consequatur fuga nobis dolor nisi.",
                            Email = "Malachi72@gmail.com",
                            Logo = "https://picsum.photos/640/480/?image=412",
                            Name = "Kemmer LLC",
                            PhoneNumber = "0932874165"
                        },
                        new
                        {
                            Id = new Guid("c1a84499-334d-44a3-8d2b-dd99b4559baf"),
                            Address = "4771 Orn Spurs, Port Theofort, Portugal",
                            Description = "Eius quam id corporis magni quasi non hic tempora eligendi.",
                            Email = "Winnifred_Reilly@gmail.com",
                            Logo = "https://picsum.photos/640/480/?image=269",
                            Name = "Quitzon and Sons",
                            PhoneNumber = "0977695046"
                        });
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AppRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AppUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AppUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens", (string)null);
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Core.Entities.ProductImage", b =>
                {
                    b.HasOne("Product", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Core.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Core.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
